function [Y,Xf,Af] = trainscg5__518-Dec-2021(X,~,~)
%TRAINSCG5__518-DEC-2021 neural network simulation function.
%
% Auto-generated by MATLAB, 18-Dec-2021 18:24:10.
% 
% [Y] = trainscg5__518-Dec-2021(X,~,~) takes these arguments:
% 
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = 5xQ matrix, input #1 at timestep ts.
% 
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = 2xQ matrix, output #1 at timestep ts.
% 
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [0.50826608;0.75224505;0.25240559;0.7524299;0.250911845];
x1_step1.gain = [0.33388061039706;0.400593992760585;0.364089031557419;0.400510983928626;0.363726553603256];
x1_step1.ymin = -1;

% Layer 1
b1 = [-0.70503389527285675875;-0.72441462043719406783;0.30539589243980452826;0.85624540683192407187;-0.92406058729935114382];
IW1_1 = [1.0791010808793188858 -0.2400829727426109228 -1.5195075908922492935 -0.61579762353648692663 -0.11412775105555707233;0.56651876448620863691 -0.54957637785662083463 -1.4068781715850560143 1.044521130454126423 1.2057306111623606881;1.4917458277713482317 0.45589187029642513904 1.6905442535091694811 0.038895409682353485059 -0.13040939000154189165;0.14304249283658240777 -0.36037000844486399842 0.5615000097752755881 2.153387027045690072 -0.76341143392732668804;-1.1975184102558007471 -0.89191760959764088135 1.7525779793093112513 0.37698591033570211239 0.29229985970274913187];

% Layer 2
b2 = [-1.4455085213463485516;1.0320664740779117441;0.6658140757264651155;-0.93578505982301030119;1.7717043260614009359];
LW2_1 = [0.26976667429959755307 1.3444636240784000325 1.0993360180815596738 0.24052873984327921564 -1.5010519014719920783;-0.33906879026769243257 0.31799916197407618323 -0.48294541705332355574 2.2745188643161027287 -0.57771109554475086334;-0.33325716420780138183 0.79286683062103324726 0.20216338481022985696 -2.1833650778396762604 -0.68192056852939508804;-1.5570221058547550896 -0.34175665125398480004 0.93887681623696273014 -1.2371576033687474716 0.031645454106174253361;0.92461073433251661502 0.58351391488724546619 0.29571542887695706492 0.011766028347163115519 -1.4659501992995487285];

% Layer 3
b3 = [0.024591693433771655286;0.034087119647684703538];
LW3_2 = [0.54311735232897484504 0.10746832112986857977 -0.29612909627937528123 0.44333215581246232517 0.40145194220475688418;0.18788748516543776756 0.65733161932914085934 0.51540075480439262456 0.56205567364750141923 -0.24910992418468996812];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = [0.585808911511449;0.568900823163935];
y1_step1.xoffset = [-1.78720142;-6.54522631];

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
  X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
  Q = size(X{1},2); % samples/series
else
  Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS

    % Input 1
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = tansig_apply(repmat(b2,1,Q) + LW2_1*a1);
    
    % Layer 3
    a3 = repmat(b3,1,Q) + LW3_2*a2;
    
    % Output 1
    Y{1,ts} = mapminmax_reverse(a3,y1_step1);
end

% Final Delay States
Xf = cell(1,0);
Af = cell(3,0);

% Format Output Arguments
if ~isCellX
  Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
  y = bsxfun(@minus,x,settings.xoffset);
  y = bsxfun(@times,y,settings.gain);
  y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
  a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
  x = bsxfun(@minus,y,settings.ymin);
  x = bsxfun(@rdivide,x,settings.gain);
  x = bsxfun(@plus,x,settings.xoffset);
end
