function error = squareErrorGeo(geo1, geo2)
%Function that takes into account that the order of the windows doesn't
%matter. So the error of [1 3 3 5 3],[1 5 3 3 3] is zero.
error = min( ...
    norm(geo1 - geo2), ...
    norm([geo1(1) - geo2(1) ...
    geo1(2) - geo2(4) ...
    geo1(3) - geo2(5) ...
    geo1(4) - geo2(2) ...
    geo1(5) - geo2(3)]));
end